# Generated by Django 4.0.3 on 2022-04-25 09:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Hindi', 'Hindi'), ('Urdu', 'Urdu')], default=(('Bangla', 'Bangla'), ('English', 'English'), ('Hindi', 'Hindi'), ('Urdu', 'Urdu')), max_length=100),
        ),
    ]
